0 silly input [ 'coverage' ]
1 silly flags { _: [ 'run' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   script: 'coverage',
1 silly flags   args: [] }
2 verbose rootPath /Volumes/DATI/Users/Shogun/Lavoro/nearForm/trail
3 info version 2.11.0
4 silly existsSync /Volumes/DATI/Users/Shogun/Lavoro/nearForm/trail/VERSION
5 info versioning independent
6 silly initialize attempt
7 silly initialize success
8 silly execute attempt
9 silly runScriptInDir coverage [] trail-core
10 silly getExecOpts { cwd: '/Volumes/DATI/Users/Shogun/Lavoro/nearForm/trail/packages/trail-core' }
11 error coverage Errored while running script in '@nearform/trail-core'
12 error execute callback with error
13 error Error: Command failed: npm run coverage
13 error FAIL test/index.test.js
13 error   ● TrailsManager › .performDatabaseOperations › should rollback transaction when something bad happens
13 error
13 error     expect(received).toEqual(expected)
13 error
13 error     Expected value to equal:
13 error       "rollback please"
13 error     Received:
13 error       "syntax error at or near \"where\""
13 error
13 error       49 |         })
13 error       50 |       } catch (e) {
13 error     > 51 |         expect(e.message).toEqual('rollback please')
13 error       52 |       }
13 error       53 |
13 error       54 |       const newCount = parseInt((await this.subject.performDatabaseOperations(client => client.query('SELECT COUNT(*) FROM trails'), false)).rows[0].count, 0)
13 error
13 error       at Object.test (test/index.test.js:51:27)
13 error
13 error   ● TrailsManager › .performDatabaseOperations › should not use transaction if requested to
13 error
13 error     expect(received).toEqual(expected)
13 error
13 error     Expected value to equal:
13 error       "rollback please"
13 error     Received:
13 error       "syntax error at or near \"where\""
13 error
13 error       69 |         }, false)
13 error       70 |       } catch (e) {
13 error     > 71 |         expect(e.message).toEqual('rollback please')
13 error       72 |       }
13 error       73 |
13 error       74 |       const newCount = parseInt((await this.subject.performDatabaseOperations(client => client.query('SELECT COUNT(*) FROM trails'), false)).rows[0].count, 0)
13 error
13 error       at Object.test (test/index.test.js:71:27)
13 error
13 error   ● TrailsManager › .insert › should accept a single argument
13 error
13 error     error: column "where" of relation "trails" does not exist
13 error
13 error       at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:545:11)
13 error       at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:370:19)
13 error       at Socket.<anonymous> (node_modules/pg/lib/connection.js:113:22)
13 error
13 error   ● TrailsManager › .get › should retrieve an existing trail
13 error
13 error     error: column "where" of relation "trails" does not exist
13 error
13 error       at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:545:11)
13 error       at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:370:19)
13 error       at Socket.<anonymous> (node_modules/pg/lib/connection.js:113:22)
13 error
13 error   ● TrailsManager › .get › should return null if trail doesn't exist when performing a get
13 error
13 error     error: column "where" does not exist
13 error
13 error       at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:545:11)
13 error       at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:370:19)
13 error       at Socket.<anonymous> (node_modules/pg/lib/connection.js:113:22)
13 error
13 error   ● TrailsManager › .get › should raise an error when something bad happens
13 error
13 error     error: column "where" of relation "trails" does not exist
13 error
13 error       at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:545:11)
13 error       at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:370:19)
13 error       at Socket.<anonymous> (node_modules/pg/lib/connection.js:113:22)
13 error
13 error   ● TrailsManager › .update › should be able to update an existing trail
13 error
13 error     error: column "where" of relation "trails" does not exist
13 error
13 error       at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:545:11)
13 error       at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:370:19)
13 error       at Socket.<anonymous> (node_modules/pg/lib/connection.js:113:22)
13 error
13 error   ● TrailsManager › .update › should raise an error when something bad happens
13 error
13 error     error: column "where" of relation "trails" does not exist
13 error
13 error       at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:545:11)
13 error       at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:370:19)
13 error       at Socket.<anonymous> (node_modules/pg/lib/connection.js:113:22)
13 error
13 error   ● TrailsManager › .delete › should be able to delete an existing trail
13 error
13 error     error: column "where" of relation "trails" does not exist
13 error
13 error       at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:545:11)
13 error       at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:370:19)
13 error       at Socket.<anonymous> (node_modules/pg/lib/connection.js:113:22)
13 error
13 error   ● TrailsManager › .delete › should raise an error when something bad happens
13 error
13 error     error: column "where" of relation "trails" does not exist
13 error
13 error       at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:545:11)
13 error       at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:370:19)
13 error       at Socket.<anonymous> (node_modules/pg/lib/connection.js:113:22)
13 error
13 error PASS test/trail.test.js
13 error
13 error Test Suites: 1 failed, 1 passed, 2 total
13 error Tests:       10 failed, 17 passed, 27 total
13 error Snapshots:   0 total
13 error Time:        3.099s
13 error Ran all test suites.
13 error npm ERR! code ELIFECYCLE
13 error npm ERR! errno 1
13 error npm ERR! @nearform/trail-core@1.0.0 coverage: `jest -i --coverage`
13 error npm ERR! Exit status 1
13 error npm ERR!
13 error npm ERR! Failed at the @nearform/trail-core@1.0.0 coverage script.
13 error npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
13 error
13 error npm ERR! A complete log of this run can be found in:
13 error npm ERR!     /Volumes/DATI/Users/Shogun/.npm/_logs/2018-04-27T07_32_53_922Z-debug.log
13 error
13 error > @nearform/trail-core@1.0.0 coverage /Volumes/DATI/Users/Shogun/Lavoro/nearForm/trail/packages/trail-core
13 error > jest -i --coverage
13 error
13 error ----------|----------|----------|----------|----------|-------------------|
13 error File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
13 error ----------|----------|----------|----------|----------|-------------------|
13 error All files |    85.26 |    95.74 |    85.71 |       85 |                   |
13 error  index.js |    73.08 |    86.67 |    81.82 |    72.73 |... 19,121,136,138 |
13 error  trail.js |      100 |      100 |      100 |      100 |                   |
13 error ----------|----------|----------|----------|----------|-------------------|
13 error
13 error     at Promise.all.then.arr (/Volumes/DATI/Users/Shogun/Lavoro/nearForm/trail/node_modules/execa/index.js:236:11)
13 error     at <anonymous>
